local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5 #before 5.0
  publish_frequency: 2 #before 2.0
  static_map: false
  rolling_window: true
  width: 2
  height: 2
  resolution: 0.05          # increase to for higher res 0.025
  transform_tolerance: 0.5  # tune, latency in published transforms (in seconds)
  cost_scaling_factor: 10 #12    # tune, cost scaling factor
  inflation_radius: 0.45    # tune, distance at which the cost of an obstacle should be considered.
